# Generated by Django 6.0.4 on 2026-05-02 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('sub_date', models.DateTimeField(verbose_name='date submitted')),
                ('last_update_date', models.DateTimeField(verbose_name='last updated timestamp')),
                ('assigned_agent_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_complaints', to=settings.AUTH_USER_MODEL)),
                ('customer_account_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('complaint_category_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.complaintcategory')),
                ('complaint_status_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.complaintstatus')),
                ('notes', models.ManyToManyField(to='dashboard.notes')),
            ],
        ),
    ]
