# Generated by Django 6.0.4 on 2026-05-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_serviceplan_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='service_plan_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.serviceplan'),
        ),
    ]
