# Generated by Django 6.0.4 on 2026-05-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userprofile_service_plan_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='notes',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.notes'),
        ),
    ]
