# Generated by Django 6.0.4 on 2026-05-03 02:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_complaint_assigned_agent_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 3, 2, 30, 6, 965146, tzinfo=datetime.timezone.utc), verbose_name='last updated timestamp'),
        ),
        migrations.AddField(
            model_name='notes',
            name='user_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
