# Generated by Django 6.0.4 on 2026-05-03 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_notes_last_update_date_notes_user_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 3, 5, 28, 38, 706010, tzinfo=datetime.timezone.utc), verbose_name='last updated timestamp'),
        ),
    ]
