# Generated by Django 6.0.4 on 2026-05-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_notes_last_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='last_update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last updated timestamp'),
        ),
    ]
