# Generated by Django 6.0.4 on 2026-05-04 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_area_userprofile_call_userprofile_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='area_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.area'),
        ),
    ]
